In [43]:
import pandas as pd

In [44]:
## series
height = pd.Series(data = [20,25,34,27,22,25,35,23], dtype="f16")
height

0    20.0
1    25.0
2    34.0
3    27.0
4    22.0
5    25.0
6    35.0
7    23.0
dtype: float128

In [45]:
## dataframe
data = {
    "name" : ["biswajit", "om", "akash"],
    "age": [22, 23, 45],
    "city": ["bbsr", "rourkela", "delhi"]
}
df = pd.DataFrame(data)

In [46]:
## reading csv
dataset = pd.read_csv("dataset/financial_audit.csv")

## read excel
# ex = pd.read_excel("filepath")

## read json
# json = pd.read_json("filepath")

In [47]:
# first 5 rows
dataset.head()

,tx_id,audit_trail,reconciliation_status
0,TXN_5000,Client: Alice Smith | Region: London | Deposit...,CLEARED
1,TXN_5015,client=Bob Jones; region = Paris; deposit=300,CLEARED
2,TXN_5030,Client: Charlie Brown; Region: TOKYO; Amount: ...,CLEARED
3,TXN_5045,Client: Diana Prince; Region: Gotham; Deposit:...,CLEARED
4,TXN_5060,Client: Evan Wright | Region: Berlin | Deposit...,CLEARED

In [48]:
## first 10 rows
dataset.head(10)

,tx_id,audit_trail,reconciliation_status
0,TXN_5000,Client: Alice Smith | Region: London | Deposit...,CLEARED
1,TXN_5015,client=Bob Jones; region = Paris; deposit=300,CLEARED
2,TXN_5030,Client: Charlie Brown; Region: TOKYO; Amount: ...,CLEARED
3,TXN_5045,Client: Diana Prince; Region: Gotham; Deposit:...,CLEARED
4,TXN_5060,Client: Evan Wright | Region: Berlin | Deposit...,CLEARED
5,TXN_5075,Client: Fiona Gallagher; Region: Chicago; Depo...,CLEARED
6,TXN_5090,Client: George Clark | Region: sydney | Deposi...,CLEARED
7,TXN_5105,Client: Hannah Abbott | Region: Boston | Depos...,REJECTED
8,TXN_5120,client=Ian Malcolm; region = ; deposit=500.00,CLEARED
9,TXN_5135,Client: Julia Roberts; Region: Hollywood; Depo...,CLEARED

In [49]:
## last rows
dataset.tail()

,tx_id,audit_trail,reconciliation_status
5,TXN_5075,Client: Fiona Gallagher; Region: Chicago; Depo...,CLEARED
6,TXN_5090,Client: George Clark | Region: sydney | Deposi...,CLEARED
7,TXN_5105,Client: Hannah Abbott | Region: Boston | Depos...,REJECTED
8,TXN_5120,client=Ian Malcolm; region = ; deposit=500.00,CLEARED
9,TXN_5135,Client: Julia Roberts; Region: Hollywood; Depo...,CLEARED

In [50]:
## whole dataset
dataset

,tx_id,audit_trail,reconciliation_status
0,TXN_5000,Client: Alice Smith | Region: London | Deposit...,CLEARED
1,TXN_5015,client=Bob Jones; region = Paris; deposit=300,CLEARED
2,TXN_5030,Client: Charlie Brown; Region: TOKYO; Amount: ...,CLEARED
3,TXN_5045,Client: Diana Prince; Region: Gotham; Deposit:...,CLEARED
4,TXN_5060,Client: Evan Wright | Region: Berlin | Deposit...,CLEARED
5,TXN_5075,Client: Fiona Gallagher; Region: Chicago; Depo...,CLEARED
6,TXN_5090,Client: George Clark | Region: sydney | Deposi...,CLEARED
7,TXN_5105,Client: Hannah Abbott | Region: Boston | Depos...,REJECTED
8,TXN_5120,client=Ian Malcolm; region = ; deposit=500.00,CLEARED
9,TXN_5135,Client: Julia Roberts; Region: Hollywood; Depo...,CLEARED

In [51]:
## shape
dataset.shape

(10, 3)

In [52]:
## columns
dataset.columns

Index(['tx_id', 'audit_trail', 'reconciliation_status'], dtype='str')

In [53]:
## information
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   tx_id                  10 non-null     str
 1   audit_trail            10 non-null     str
 2   reconciliation_status  10 non-null     str
dtypes: str(3)
memory usage: 372.0 bytes

In [54]:
## statistics
dataset.describe()

,tx_id,audit_trail,reconciliation_status
count,10,10,10
unique,10,10,2
top,TXN_5000,Client: Alice Smith | Region: London | Deposit...,CLEARED
freq,1,1,9

In [55]:
## datatypes
dataset.dtypes

tx_id                    str
audit_trail              str
reconciliation_status    str
dtype: object

In [56]:
## creating new column
dataset["country"] = ["england ", "FRance", "Japa n  ", "", " ", "USA", "AustraliA", "Usa", "India", "USA"]
dataset

,tx_id,audit_trail,reconciliation_status,country
0,TXN_5000,Client: Alice Smith | Region: London | Deposit...,CLEARED,england
1,TXN_5015,client=Bob Jones; region = Paris; deposit=300,CLEARED,FRance
2,TXN_5030,Client: Charlie Brown; Region: TOKYO; Amount: ...,CLEARED,Japa n
3,TXN_5045,Client: Diana Prince; Region: Gotham; Deposit:...,CLEARED,
4,TXN_5060,Client: Evan Wright | Region: Berlin | Deposit...,CLEARED,
5,TXN_5075,Client: Fiona Gallagher; Region: Chicago; Depo...,CLEARED,USA
6,TXN_5090,Client: George Clark | Region: sydney | Deposi...,CLEARED,AustraliA
7,TXN_5105,Client: Hannah Abbott | Region: Boston | Depos...,REJECTED,Usa
8,TXN_5120,client=Ian Malcolm; region = ; deposit=500.00,CLEARED,India
9,TXN_5135,Client: Julia Roberts; Region: Hollywood; Depo...,CLEARED,USA

In [57]:
## drops from a copy 
dataset.drop(columns = ["country"])
dataset

,tx_id,audit_trail,reconciliation_status,country
0,TXN_5000,Client: Alice Smith | Region: London | Deposit...,CLEARED,england
1,TXN_5015,client=Bob Jones; region = Paris; deposit=300,CLEARED,FRance
2,TXN_5030,Client: Charlie Brown; Region: TOKYO; Amount: ...,CLEARED,Japa n
3,TXN_5045,Client: Diana Prince; Region: Gotham; Deposit:...,CLEARED,
4,TXN_5060,Client: Evan Wright | Region: Berlin | Deposit...,CLEARED,
5,TXN_5075,Client: Fiona Gallagher; Region: Chicago; Depo...,CLEARED,USA
6,TXN_5090,Client: George Clark | Region: sydney | Deposi...,CLEARED,AustraliA
7,TXN_5105,Client: Hannah Abbott | Region: Boston | Depos...,REJECTED,Usa
8,TXN_5120,client=Ian Malcolm; region = ; deposit=500.00,CLEARED,India
9,TXN_5135,Client: Julia Roberts; Region: Hollywood; Depo...,CLEARED,USA

In [40]:
## permanent drop
dataset.drop(columns=["country"], inplace=True)
dataset

,tx_id,audit_trail,reconciliation_status
0,TXN_5000,Client: Alice Smith | Region: London | Deposit...,CLEARED
1,TXN_5015,client=Bob Jones; region = Paris; deposit=300,CLEARED
2,TXN_5030,Client: Charlie Brown; Region: TOKYO; Amount: ...,CLEARED
3,TXN_5045,Client: Diana Prince; Region: Gotham; Deposit:...,CLEARED
4,TXN_5060,Client: Evan Wright | Region: Berlin | Deposit...,CLEARED
5,TXN_5075,Client: Fiona Gallagher; Region: Chicago; Depo...,CLEARED
6,TXN_5090,Client: George Clark | Region: sydney | Deposi...,CLEARED
7,TXN_5105,Client: Hannah Abbott | Region: Boston | Depos...,REJECTED
8,TXN_5120,client=Ian Malcolm; region = ; deposit=500.00,CLEARED
9,TXN_5135,Client: Julia Roberts; Region: Hollywood; Depo...,CLEARED

In [58]:
## creating new column
dataset["country"] = ["england ", "FRance", "Japa n  ", "", " ", "USA", "AustraliA", "Usa", "India", "USA"]
dataset

,tx_id,audit_trail,reconciliation_status,country
0,TXN_5000,Client: Alice Smith | Region: London | Deposit...,CLEARED,england
1,TXN_5015,client=Bob Jones; region = Paris; deposit=300,CLEARED,FRance
2,TXN_5030,Client: Charlie Brown; Region: TOKYO; Amount: ...,CLEARED,Japa n
3,TXN_5045,Client: Diana Prince; Region: Gotham; Deposit:...,CLEARED,
4,TXN_5060,Client: Evan Wright | Region: Berlin | Deposit...,CLEARED,
5,TXN_5075,Client: Fiona Gallagher; Region: Chicago; Depo...,CLEARED,USA
6,TXN_5090,Client: George Clark | Region: sydney | Deposi...,CLEARED,AustraliA
7,TXN_5105,Client: Hannah Abbott | Region: Boston | Depos...,REJECTED,Usa
8,TXN_5120,client=Ian Malcolm; region = ; deposit=500.00,CLEARED,India
9,TXN_5135,Client: Julia Roberts; Region: Hollywood; Depo...,CLEARED,USA

In [60]:
dataset.to_csv("dataset/modified_audit.csv", index=False)