In [21]:
import pandas as pd

employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "DeptID": [1, 2, 1, 3]
})

print(employees)

   EmpID     Name  DeptID
0    101    Alice       1
1    102      Bob       2
2    103  Charlie       1
3    104    David       3

In [22]:
departments = pd.DataFrame({
    "DeptID": [1, 2, 4],
    "Department": ["IT", "HR", "Marketing"]
})

print(departments)

   DeptID Department
0       1         IT
1       2         HR
2       4  Marketing

In [3]:
## merge
pd.merge(employees, departments, on = "DeptID")

   EmpID     Name  DeptID Department
0    101    Alice       1         IT
1    102      Bob       2         HR
2    103  Charlie       1         IT

In [ ]:
result = pd.merge(
    employees,
    departments,
    on="DeptID",
    how="inner"
)

print(result)

   EmpID     Name  DeptID Department
0    101    Alice       1         IT
1    102      Bob       2         HR
2    103  Charlie       1         IT

In [ ]:
## inner join (default)
result = pd.merge(
    employees,
    departments,
    on = "DeptID",
    how="left"
)
print(result)

   EmpID     Name  DeptID Department
0    101    Alice       1         IT
1    102      Bob       2         HR
2    103  Charlie       1         IT
3    104    David       3        NaN

In [6]:
## right join
result = pd.merge(
    employees,
    departments,
    on = "DeptID",
    how="right"
)
print(result)

   EmpID     Name  DeptID Department
0  101.0    Alice       1         IT
1  103.0  Charlie       1         IT
2  102.0      Bob       2         HR
3    NaN      NaN       4  Marketing

In [ ]:
## outer join (keeps everything)
result = pd.merge(
    employees,
    departments,
    on = "DeptID",
    how="outer"
)
print(result)

   EmpID     Name  DeptID Department
0  101.0    Alice       1         IT
1  103.0  Charlie       1         IT
2  102.0      Bob       2         HR
3  104.0    David       3        NaN
4    NaN      NaN       4  Marketing

In [ ]:
## merge on different column name use left_on and right_on
pd.merge(
    employees,
    departments,
    left_on="DeptID",
    right_on="DeptID"
)

   EmpID     Name  DeptID Department
0    101    Alice       1         IT
1    102      Bob       2         HR
2    103  Charlie       1         IT

In [13]:
## merge on multiple columns (both column names should match)
employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "city": ["Delhi", "Banglore", "Hyderabad", "Bhubaneswar"],
    "DeptID": [1, 2, 1, 3]
})
departments = pd.DataFrame({
    "DeptID": [1, 2, 4],
    "Department": ["IT", "HR", "Marketing"],
    "city": ["Delhi", "Banglore", "Pune"]
})
merged_df = pd.merge(
    employees,
    departments,
    on=["DeptID", "city"]
)
print(merged_df)

   EmpID   Name      city  DeptID Department
0    101  Alice     Delhi       1         IT
1    102    Bob  Banglore       2         HR

In [ ]:
## duplicate column names
pd.merge(
    employees,
    departments,
    on = "DeptID",
    suffixes=("_emp","_cit")
)

   EmpID     Name   city_emp  DeptID Department  city_cit
0    101    Alice      Delhi       1         IT     Delhi
1    102      Bob   Banglore       2         HR  Banglore
2    103  Charlie  Hyderabad       1         IT     Delhi

In [15]:
## concatenate
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob"]
})

df2 = pd.DataFrame({
    "Name": ["Charlie", "David"]
})
pd.concat([df1, df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [16]:
pd.concat(
    [df1, df2],
    ignore_index=True
)

      Name
0    Alice
1      Bob
2  Charlie
3    David

In [ ]:
## horizontal concat
pd.concat(
    [df1, df2],
    axis=1
)

    Name     Name
0  Alice  Charlie
1    Bob    David

In [27]:
## join
employee = employees.set_index("DeptID")
salary = departments.set_index("DeptID")

employee.join(salary).reset_index()

   DeptID  EmpID     Name Department
0       1    101    Alice         IT
1       2    102      Bob         HR
2       1    103  Charlie         IT
3       3    104    David        NaN

In [28]:
## merge indicator
pd.merge(
    employees,
    departments,
    on="DeptID",
    how="outer",
    indicator=True
)

   EmpID     Name  DeptID Department      _merge
0  101.0    Alice       1         IT        both
1  103.0  Charlie       1         IT        both
2  102.0      Bob       2         HR        both
3  104.0    David       3        NaN   left_only
4    NaN      NaN       4  Marketing  right_only

In [29]:
## validate merge
pd.merge(
    employees,
    departments,
    on="DeptID",
    validate="many_to_one"
)

   EmpID     Name  DeptID Department
0    101    Alice       1         IT
1    102      Bob       2         HR
2    103  Charlie       1         IT