In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Employee": ["Alice","Bob","Charlie","David","Eva"],
    "Salary":[30000,55000,70000,45000,80000],
    "Age":[22,28,35,30,26],
    "JoinDate":[
        "2023-01-15",
        "2022-08-20",
        "2021-03-10",
        "2023-11-01",
        "2020-07-18"
    ]
})

print(df)

  Employee  Salary  Age    JoinDate
0    Alice   30000   22  2023-01-15
1      Bob   55000   28  2022-08-20
2  Charlie   70000   35  2021-03-10
3    David   45000   30  2023-11-01
4      Eva   80000   26  2020-07-18

In [3]:
df["JoinDate"].dtype

In [4]:
df["JoinDate"] = pd.to_datetime(df["JoinDate"])

In [5]:
df.dtypes

Employee               str
Salary               int64
Age                  int64
JoinDate    datetime64[us]
dtype: object

In [6]:
df["Year"] = df["JoinDate"].dt.year    ## adding new column as year

In [7]:
df

  Employee  Salary  Age   JoinDate  Year
0    Alice   30000   22 2023-01-15  2023
1      Bob   55000   28 2022-08-20  2022
2  Charlie   70000   35 2021-03-10  2021
3    David   45000   30 2023-11-01  2023
4      Eva   80000   26 2020-07-18  2020

In [8]:
df["Month"] = df["JoinDate"].dt.month    ## adding new column as month
df["Day"] = df["JoinDate"].dt.day    ## adding new column as day
df["Weekday"] = df["JoinDate"].dt.day_name()    ## adding new column as day name
df

  Employee  Salary  Age   JoinDate  Year  Month  Day    Weekday
0    Alice   30000   22 2023-01-15  2023      1   15     Sunday
1      Bob   55000   28 2022-08-20  2022      8   20   Saturday
2  Charlie   70000   35 2021-03-10  2021      3   10  Wednesday
3    David   45000   30 2023-11-01  2023     11    1  Wednesday
4      Eva   80000   26 2020-07-18  2020      7   18   Saturday

In [9]:
df[df["JoinDate"] > "2023-01-01"]

  Employee  Salary  Age   JoinDate  Year  Month  Day    Weekday
0    Alice   30000   22 2023-01-15  2023      1   15     Sunday
3    David   45000   30 2023-11-01  2023     11    1  Wednesday

In [15]:
### apply()
df["Bonus"] = df["Salary"].apply(
    lambda x: x*0.1
)
df

  Employee  Salary  Age   JoinDate  Year  Month  Day    Weekday   Bonus
0    Alice   30000   22 2023-01-15  2023      1   15     Sunday  3000.0
1      Bob   55000   28 2022-08-20  2022      8   20   Saturday  5500.0
2  Charlie   70000   35 2021-03-10  2021      3   10  Wednesday  7000.0
3    David   45000   30 2023-11-01  2023     11    1  Wednesday  4500.0
4      Eva   80000   26 2020-07-18  2020      7   18   Saturday  8000.0

In [ ]:
## map()  works on series only
city = pd.Series([
    "Delhi",
    "Mumbai",
    "Kolkata"
])

In [17]:
city.map({
    "Delhi":"DL",
    "Mumbai":"MH",
    "Kolkata":"WB"
})

0    DL
1    MH
2    WB
dtype: str

In [18]:
## apply() on Entire Rows
def calculate_tax(row):

    if row["Salary"] > 60000:
        return row["Salary"] * 0.30

    return row["Salary"] * 0.10

df["Tax"] = df.apply(
    calculate_tax,
    axis=1
)

In [19]:
df

,Employee,Salary,Age,JoinDate,Year,Month,Day,Weekday,Bonus,Tax
0,Alice,30000,22,2023-01-15,2023,1,15,Sunday,3000.0,3000.0
1,Bob,55000,28,2022-08-20,2022,8,20,Saturday,5500.0,5500.0
2,Charlie,70000,35,2021-03-10,2021,3,10,Wednesday,7000.0,21000.0
3,David,45000,30,2023-11-01,2023,11,1,Wednesday,4500.0,4500.0
4,Eva,80000,26,2020-07-18,2020,7,18,Saturday,8000.0,24000.0

In [21]:
## replace()
df["Employee"] = df["Employee"].replace(
    "Bob",
    "John"
)
df

,Employee,Salary,Age,JoinDate,Year,Month,Day,Weekday,Bonus,Tax
0,Alice,30000,22,2023-01-15,2023,1,15,Sunday,3000.0,3000.0
1,John,55000,28,2022-08-20,2022,8,20,Saturday,5500.0,5500.0
2,Charlie,70000,35,2021-03-10,2021,3,10,Wednesday,7000.0,21000.0
3,David,45000,30,2023-11-01,2023,11,1,Wednesday,4500.0,4500.0
4,Eva,80000,26,2020-07-18,2020,7,18,Saturday,8000.0,24000.0

In [ ]:
## cut()
df["SalaryBand"] = pd.cut(
    df["Salary"],
    bins=[0,40000,60000,100000],
    labels=["Low","Medium","High"]
)
df

,Employee,Salary,Age,JoinDate,Year,Month,Day,Weekday,Bonus,Tax,SalaryBand
0,Alice,30000,22,2023-01-15,2023,1,15,Sunday,3000.0,3000.0,Low
1,John,55000,28,2022-08-20,2022,8,20,Saturday,5500.0,5500.0,Medium
2,Charlie,70000,35,2021-03-10,2021,3,10,Wednesday,7000.0,21000.0,High
3,David,45000,30,2023-11-01,2023,11,1,Wednesday,4500.0,4500.0,Medium
4,Eva,80000,26,2020-07-18,2020,7,18,Saturday,8000.0,24000.0,High

In [ ]:
## qcut()    divides equally
pd.qcut(
    df["Salary"],
    q=4
)
df

,Employee,Salary,Age,JoinDate,Year,Month,Day,Weekday,Bonus,Tax,SalaryBand
0,Alice,30000,22,2023-01-15,2023,1,15,Sunday,3000.0,3000.0,Low
1,John,55000,28,2022-08-20,2022,8,20,Saturday,5500.0,5500.0,Medium
2,Charlie,70000,35,2021-03-10,2021,3,10,Wednesday,7000.0,21000.0,High
3,David,45000,30,2023-11-01,2023,11,1,Wednesday,4500.0,4500.0,Medium
4,Eva,80000,26,2020-07-18,2020,7,18,Saturday,8000.0,24000.0,High

In [26]:
## where()
df["Salary"] = df["Salary"].where(
    df["Salary"] >= 50000
)
df

,Employee,Salary,Age,JoinDate,Year,Month,Day,Weekday,Bonus,Tax,SalaryBand
0,Alice,NaN,22,2023-01-15,2023,1,15,Sunday,3000.0,3000.0,Low
1,John,55000.0,28,2022-08-20,2022,8,20,Saturday,5500.0,5500.0,Medium
2,Charlie,70000.0,35,2021-03-10,2021,3,10,Wednesday,7000.0,21000.0,High
3,David,NaN,30,2023-11-01,2023,11,1,Wednesday,4500.0,4500.0,Medium
4,Eva,80000.0,26,2020-07-18,2020,7,18,Saturday,8000.0,24000.0,High

In [28]:
## np.select()    Multiple conditions
conditions = [
    df["Salary"] >= 70000,
    df["Salary"] >= 50000
]

choices = [
    "High",
    "Medium"
]

df["Level"] = np.select(
    conditions,
    choices,
    default="Low"
)
df

,Employee,Salary,Age,JoinDate,Year,Month,Day,Weekday,Bonus,Tax,SalaryBand,Level
0,Alice,NaN,22,2023-01-15,2023,1,15,Sunday,3000.0,3000.0,Low,Low
1,John,55000.0,28,2022-08-20,2022,8,20,Saturday,5500.0,5500.0,Medium,Medium
2,Charlie,70000.0,35,2021-03-10,2021,3,10,Wednesday,7000.0,21000.0,High,High
3,David,NaN,30,2023-11-01,2023,11,1,Wednesday,4500.0,4500.0,Medium,Low
4,Eva,80000.0,26,2020-07-18,2020,7,18,Saturday,8000.0,24000.0,High,High

In [29]:
## assign()
df = df.assign(
    Bonus=df["Salary"] * 0.1
)
df

,Employee,Salary,Age,JoinDate,Year,Month,Day,Weekday,Bonus,Tax,SalaryBand,Level
0,Alice,NaN,22,2023-01-15,2023,1,15,Sunday,NaN,3000.0,Low,Low
1,John,55000.0,28,2022-08-20,2022,8,20,Saturday,5500.0,5500.0,Medium,Medium
2,Charlie,70000.0,35,2021-03-10,2021,3,10,Wednesday,7000.0,21000.0,High,High
3,David,NaN,30,2023-11-01,2023,11,1,Wednesday,NaN,4500.0,Medium,Low
4,Eva,80000.0,26,2020-07-18,2020,7,18,Saturday,8000.0,24000.0,High,High